# Generated by Django 4.0.1 on 2022-01-27 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_docente_curso_docente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('age', models.PositiveSmallIntegerField()),
                ('curso', models.ManyToManyField(to='academico.Curso')),
            ],
        ),
    ]
